### ISSUE TITLE
Which licence is this released under?

### ISSUE THREAD

**Issue by spdegabrielle** [shawnw/racket-scapegoat-tree#1]
Which licence is this released under?

To make it easier for others to use I’d suggest the same terms as racket but obviously it is your choice

E.g. 
```
This code is available according to same terms as Racket:

http://download.racket-lang.org/license.html

Copyright © Your name here
```

**Comment by shawnw** [comment]
It's in the info.rkt file. Looks like I forgot to add the license files themselves to the repo.

**Comment by spdegabrielle** [comment]
Thank you 😁
